name: blih # you probably want to 'snapcraft register <name>'
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Bocal Lightweight Interface for Humans # 79 char long summary
description: |
  blih repository [-h] {create,delete,info,list,getacl,setacl}
  blih sshkey [-h] {upload,list,delete}

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  blih:
    command: blih

parts:
  blih:
    source: .
    plugin: python
    python-version: python2
